name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: vinaykumarnomula
        password: V$arpv1234

    - name: Pull OWASP ZAP Docker image
      run: docker pull zaproxy/zap-weekly

    - name: Run OWASP ZAP scan
      run: |
        docker run -v $(pwd):/zap/wrk/:rw -t zaproxy/zap-weekly zap-baseline.py -t https://demo.testfire.net/ -r zap_report.html -z "auth.loginurl=https://demo.testfire.net/login" -z "auth.username=admin" -z "auth.password=admin"

    - name: Upload ZAP report
      uses: actions/upload-artifact@v3
      with:
        name: zap-report
        path: zap_report.html
