name: OWASP ZAP Integration with GitHub Actions

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          target: 'http://testphp.vulnweb.com/'
          cmd_options: '-a'
